### ISSUE TITLE
Reproduce the informative features analysis?

### ISSUE THREAD

**Issue by ohaijen** [lucaslie/torchprune#5]
Dear authors,

Thanks for the nice paper and code repo. Is there a way to use this code to reproduce the informative features analysis (Lost in pruning / what is preserved)?

Thanks in advance!

**Comment by lucaslie** [comment]
Hi, 
Thanks for your interest in our paper and code repo. :) 

Unfortunately, I never got around to clean up the code for these experiments. But I added what I have to the repo here: 

https://github.com/lucaslie/torchprune/tree/main/paper/lost/script/sis_experimental

I don't know if it runs bug-free since I haven't tested it for a while but hopefully, you should be able to modify it and get it to run one way or the other.

**Comment by ohaijen** [comment]
Hi Lucas, no worries at all :) Thanks a lot for sharing what you have!
